# Generated by Django 4.0.6 on 2022-07-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
